Solution
mate-academy/py-count-occurrences pull request #1043
Opened 2023-11-29 10:44 UTC by xrkxdd

2023-11-29 11:29 UTC, ArsenPidhoretskyi requested changes

2023-11-29 11:29 UTC, ArsenPidhoretskyi commented on app/main.py
> +    return counter
Try to rewrite this in one line

2023-11-29 17:27 UTC, vsmutok requested changes

2023-11-29 17:27 UTC, vsmutok commented on app/main.py
> +    return sum(1 for char in phrase if char.lower() == letter.lower())
try to use `letter.lower().count(...)`

2023-12-01 11:03 UTC, ArsenPidhoretskyi approved these changes
Well done!

2023-12-04 20:47 UTC, closed without merging