Solution
mate-academy/py-count-occurrences pull request #1109
Opened 2023-12-27 19:53 UTC by Oleksandr147

2023-12-27 19:56 UTC, Oleksandr147 commented on app/main.py
> +    for char in phrase:
rename to 'character'

2023-12-27 19:56 UTC, Oleksandr147 commented on app/main.py
> +            counter += 1
add a line

2023-12-28 09:10 UTC, EdAlekseiev requested changes

2023-12-28 09:10 UTC, EdAlekseiev commented on app/main.py
> +            counter += 1
Write this in one line

2023-12-31 15:00 UTC, Oleksandr147 commented
Already created new pull request, please check


On Thu, Dec 28, 2023 at 11:10 AM Eduard Alekseiev ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In app/main.py
> <https://github.com/mate-academy/py-count-occurrences/pull/1109#discussion_r1437497089>
> :
>
> > +    counter = 0
> +    for character in phrase:
> +        if character.lower() == letter.lower():
> +            counter += 1
>
> Write this in one line
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mate-academy/py-count-occurrences/pull/1109#pullrequestreview-1797838856>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYJIZQHTZEIITMMTPADRFTLYLUZPLAVCNFSM6AAAAABBEWO77KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOJXHAZTQOBVGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-12-31 15:08 UTC, closed without merging