Solution
mate-academy/py-count-occurrences pull request #1175
Opened 2024-01-09 18:13 UTC by shafran-andriy

2024-01-09 19:21 UTC, EdAlekseiev requested changes
Rewrite your function to one line with using method `count` of string

2024-01-09 19:49 UTC, shafran-andriy commented
Function has been rewrited with using method count of string

2024-01-22 18:32 UTC, EdAlekseiev requested changes
Fix flake8, please

2024-01-22 18:59 UTC, EdAlekseiev requested changes
Flake8 still has not been fixed

2024-01-22 18:59 UTC, EdAlekseiev commented on app/main.py
> +
Delete these lines
```suggestion
```

2024-01-22 19:20 UTC, EdAlekseiev requested changes
Fix flake8

2024-01-22 19:31 UTC, EdAlekseiev approved these changes
Good job

2024-07-30 11:06 UTC, closed without merging