Solution
mate-academy/py-count-occurrences pull request #1236
Opened 2024-02-02 18:17 UTC by sserkov84

2024-02-03 11:18 UTC, NazarSheremet requested changes
Need to optimіze solution

2024-02-03 11:18 UTC, NazarSheremet commented on app/main.py
> +            count += 1
The solution is correct, but it's better to use the `count()` function as it will simplify the code.

2024-02-03 18:12 UTC, sserkov84 commented
Optimized as needed

2024-02-06 19:29 UTC, closed without merging

2024-02-07 12:17 UTC, YuriiSmolii approved these changes
Well done.