Solution
mate-academy/py-count-occurrences pull request #1389
Opened 2024-03-16 09:08 UTC by Aspafr77

2024-03-16 13:22 UTC, vsmutok requested changes

2024-03-16 13:22 UTC, vsmutok commented on app/main.py
> +    return counter
try to write it in one line

2024-03-16 16:59 UTC, Aspafr77 commented on app/main.py
> +    return counter
Завтра напишу

2024-03-20 11:48 UTC, Aspafr77 commented
Доброго дня! Я правильно виправив?

2024-03-20 13:37 UTC, Aspafr77 commented on app/main.py
> +    return counter
Доброго дня! Я виправив. Не знаю чи правильно?

2024-03-27 06:51 UTC, closed without merging

2024-04-24 17:43 UTC, Aspafr77 commented
Щось я запутався

2024-04-24 18:20 UTC, vsmutok approved these changes
Well Done!