Solution
mate-academy/py-count-occurrences pull request #212
Opened 2022-10-28 13:12 UTC by neagarr

Hi. I have a question:
What about 3  ....pycache.... files?  What is it?

2022-10-28 14:06 UTC, Abnormaltype requested changes
it's cache of tests, you should remove it from the PR

2022-10-28 20:10 UTC, neagarr commented
looks like changed

2022-10-28 20:36 UTC, neagarr commented
Хотів ще спитати:
ям мені можна було видалити файли та запушити зміни за один комміт а не за 3?
Я спробував зробити ресет, видалив непотрібні файли але запушити не вдалося, бо HEAD знаходився "нижче" голови гілки developer. І що з цим робити я не зрозумів.

Тому я знов зробив ресет, потім видалив файли , потім безпосередньо на Гіті видаляв файл за файлом з коммітом при кожному видаленні (3 штуки). Потім зробив PULL з гіта до локального репозиторію. Паралельно воно зробило MERGE  і сформувалась теперішня гілка. Яку вже вдалося запушити в гіт.

Впевнений, що пішов костилями і хотів би зрозуміти, як би мій ментор це зробив.
Дякую

2022-10-29 23:01 UTC, neagarr commented
Дякую, вже розібрався)

2022-10-31 09:49 UTC, IvanRamyk approved these changes
Good job!

2022-10-31 20:20 UTC, closed without merging