Test_1 (Python Core)
mate-academy/py-count-occurrences pull request #686
Opened 2023-07-07 15:00 UTC by baranovr

2023-07-07 15:46 UTC, Bohdan-Salamakha requested changes
don't change tests!

2023-07-07 15:46 UTC, Bohdan-Salamakha commented on app/main.py
> +    return letter_count
use count method
https://www.w3schools.com/python/ref_string_count.asp

2023-07-20 13:06 UTC, Polyakiv-Andrey requested changes

2023-07-20 13:06 UTC, Polyakiv-Andrey commented on app/main.py
> +    return all_letters
return the answer immediately, do not create unnecessary variables

2023-07-20 13:06 UTC, Polyakiv-Andrey commented on app/main.py
> +    return all_letters
add an empty line at the end of the file

2023-07-20 13:06 UTC, Polyakiv-Andrey commented on tests/test_main.py
<img width="1067" alt="Screenshot 2023-07-20 at 16 05 00" src="https://github.com/mate-academy/py-count-occurrences/assets/117740672/8b7036de-e03c-4fa8-a9cb-8decefc4560c">
restore this file to its original state

2023-07-22 18:24 UTC, closed without merging