Develop mike sanin
mate-academy/py-count-occurrences pull request #775
Opened 2023-08-06 13:19 UTC by mikesanin

mike_sanin comment ?

2023-08-06 13:25 UTC, EdAlekseiev requested changes

2023-08-06 13:25 UTC, EdAlekseiev commented on app/main.py
> +}
Incorrect solution. Please, re-read the task requirements.

2023-08-06 15:36 UTC, YukihiroSM requested changes
The code is good, but try to remove pycache files from git repo. They are not needed.

2023-08-12 13:45 UTC, Bohdan-Salamakha requested changes
remove all pycache files/folders from github

2023-08-12 13:45 UTC, Bohdan-Salamakha commented on app/main.py
> +number_list = [1, 2]
remove this redundant code

2023-08-12 13:45 UTC, Bohdan-Salamakha commented on app/main.py
> +    return count
https://www.w3schools.com/python/ref_string_count.asp

2023-08-30 20:39 UTC, closed without merging