Add solution
mate-academy/py-count-occurrences pull request #926
Opened 2023-10-03 12:17 UTC by IlyaGrynyshyn

2023-10-03 12:21 UTC, pavlejviki requested changes

2023-10-03 12:21 UTC, pavlejviki commented on app/main.py
> +    return count
try to solve in one line using count() method

2023-10-03 14:24 UTC, Polyakiv-Andrey requested changes
delete pycashe from git

2023-10-03 17:49 UTC, viktoria-rybenchuk requested changes
rollback changes in .gitignore

2023-10-04 09:58 UTC, pavlejviki requested changes

2023-10-04 09:58 UTC, pavlejviki commented on .gitignore
> +<<<<<<< HEAD
remove redundant code

2023-10-04 10:28 UTC, viktoria-rybenchuk approved these changes
GJ!

2023-11-17 13:26 UTC, closed without merging