Solution
mate-academy/py-count-occurrences pull request #962
Opened 2023-10-22 11:38 UTC by Maxboond

2023-10-22 12:49 UTC, Dimosphen1 requested changes
Several changes were requested.

2023-10-22 12:49 UTC, Dimosphen1 commented on app/main.py
> +    for i in phrase:
Do not use single-letter variable names in your code.

2023-10-22 12:49 UTC, Dimosphen1 commented on app/main.py
> +    return count
You could try to implement this task in one line using built-in string methods and chaining to not allocate additional variables throughout your code execution.

2023-10-24 11:27 UTC, Maxboond reviewed
fix newline

2023-10-24 16:33 UTC, closed without merging